Repository SOPT-all/36-COLLABORATION-iOS-UBER, pull requests merged in 2025-05, with the labels that each got.

#4 [Add] 디자인 시스템 구축: 폰트, 컬러, 아이콘 세팅 (#3)
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
  Uber-iOS/Uber-iOS/Global/Resources/Extension/UIFont+.swift
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/Text/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/Text/point1.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/Text/point2.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/Text/primary.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/Text/sub1.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/Text/sub2.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/Text/sub3.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/Text/textWhite.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/bg/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/bg/bgBlack.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/bg/bgGray.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/bg/bgWhite.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/bg/grayscale.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/bg/graysub.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/border/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/border/borderBlack.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/btn/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/btn/btnActive.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/btn/btnInactive.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/icon/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/icon/iconActive.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/icon/iconInactive.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/icon/info1.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/icon/info2.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/icon/info3.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Color/icon/info4.colorset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Font/SUIT-Bold.otf
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Font/SUIT-ExtraBold.otf
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Font/SUIT-Medium.otf
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Font/SUIT-SemiBold.otf
  Uber-iOS/Uber-iOS/Global/Setting/Info.plist
  Uber-iOS/Uber-iOS/Presentation/ViewController.swift
Labels: 🍏영주🍏, add

#7 [Add] ConfigFile Setting (#6)
  .gitignore
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
  Uber-iOS/Uber-iOS/Global/Config/Secret.swift
  Uber-iOS/Uber-iOS/Global/Setting/Info.plist
Labels: 🧃석기🧃, add

#15 [Feat] UIbutton 익스텐션 추가
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
  Uber-iOS/Uber-iOS/Application/SceneDelegate.swift
  Uber-iOS/Uber-iOS/Global/Extension/UIButton+.swift
  Uber-iOS/Uber-iOS/Presentation/ViewController/HomeViewController.swift
  Uber-iOS/Uber-iOS/Presentation/ViewController/ViewController.swift
Labels: 🍏영주🍏, feat

#16 [Feat] 예약 정보 화면 UI 구현
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
  Uber-iOS/Uber-iOS/Global/Extension/NSMutableAttributedString+.swift
  Uber-iOS/Uber-iOS/Global/Extension/String+.swift
  Uber-iOS/Uber-iOS/Global/Extension/UILabel+.swift
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/cardImage.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/cardImage.imageset/image 1295.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/cardImage.imageset/image 1295@2x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/cardImage.imageset/image 1295@3x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/promotionImage.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/promotionImage.imageset/icon_18px@2x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/promotionImage.imageset/icon_18px@3x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/promotionImage.imageset/promotionImage.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/rightIcon.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/rightIcon.imageset/ic24@2x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/rightIcon.imageset/ic24@3x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/rightIcon.imageset/rightIcon.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/routeImage.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/routeImage.imageset/routeImage.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/routeImage.imageset/routeImage@2x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/routeImage.imageset/routeImage@3x.png
  Uber-iOS/Uber-iOS/Presentation/Reservation/ReservationInfoViewController.swift
  Uber-iOS/Uber-iOS/Presentation/Reservation/SectionView.swift
Labels: 🧃석기🧃, feat

#18 [Feat] 예약 정보 소개 함수 구현
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_child_care_32.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_child_care_32.imageset/child_care 1.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_child_care_32.imageset/child_care.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_child_care_32.imageset/ic_child_care_32.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_directions_car_32.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_directions_car_32.imageset/directions_car 1.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_directions_car_32.imageset/directions_car.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_directions_car_32.imageset/ic_directions_car_32.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_flight_32.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_flight_32.imageset/flight 1.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_flight_32.imageset/flight.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_flight_32.imageset/ic_flight_32.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_g_translate_32.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_g_translate_32.imageset/g_translate 1.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_g_translate_32.imageset/g_translate.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/ic_g_translate_32.imageset/ic_g_translate_32.png
  Uber-iOS/Uber-iOS/Presentation/CommonView/Reserve/ReserveInfoStyle.swift
  Uber-iOS/Uber-iOS/Presentation/CommonView/Reserve/ReserveInfoView.swift
Labels: 🍎휘원🍎, feat

#21 [Feat] 차량 선택 컴포넌트 UI 구현
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Vehicle/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Vehicle/guestImage.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Vehicle/guestImage.imageset/icon@2x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Vehicle/guestImage.imageset/icon@3x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Vehicle/guestImage.imageset/userImage.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Vehicle/taxiImage.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Vehicle/taxiImage.imageset/image54@2x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Vehicle/taxiImage.imageset/image54@3x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Vehicle/taxiImage.imageset/taxiImage.png
  Uber-iOS/Uber-iOS/Presentation/VehicleSelection/VehicleSelectionButton.swift
Labels: 🧃석기🧃, feat

#20 [Feat] 예약 관련 UI component
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/RecentSearch/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/RecentSearch/delete.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/RecentSearch/delete.imageset/delete 1.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/RecentSearch/delete.imageset/delete 2.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/RecentSearch/delete.imageset/delete.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/RecentSearch/time.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/RecentSearch/time.imageset/icon_24px.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/RecentSearch/time.imageset/time 1.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/RecentSearch/time.imageset/time.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/calender.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/calender.imageset/calender 1.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/calender.imageset/calender 2.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/calender.imageset/calender.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/sandclock.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/sandclock.imageset/sandclock 1.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/sandclock.imageset/sandclock 2.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/sandclock.imageset/sandclock.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/wallet.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/wallet.imageset/icon 1.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/wallet.imageset/icon 2.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/Image/Reserve/wallet.imageset/icon.png
  Uber-iOS/Uber-iOS/Presentation/RecentSearchView/RecentSearchCell.swift
  Uber-iOS/Uber-iOS/Presentation/RecentSearchView/RecentSearchHeaderView.swift
  Uber-iOS/Uber-iOS/Presentation/ReserveView/ReserveNoticeType.swift
  Uber-iOS/Uber-iOS/Presentation/ReserveView/ReserveNoticeView.swift
Labels: 🍎휘원🍎, feat

#23 [Feat] 홈뷰 구현
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
  Uber-iOS/Uber-iOS/Global/Extension/UILabel+.swift
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/account.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/account.imageset/account.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/activity.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/activity.imageset/activity.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/banner.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/banner.imageset/banner.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/calendar.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/calendar.imageset/calendar.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/car.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/car.imageset/car.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/home.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/home.imageset/home.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/next.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/next.imageset/next.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/service.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/navigation/service.imageset/service.png
  Uber-iOS/Uber-iOS/Presentation/View/DiscountBannerView.swift
  Uber-iOS/Uber-iOS/Presentation/View/HomeHeaderView .swift
  Uber-iOS/Uber-iOS/Presentation/View/ReserveBannerView.swift
  Uber-iOS/Uber-iOS/Presentation/View/ServiceButtonView.swift
  Uber-iOS/Uber-iOS/Presentation/View/TabBar.swift
  Uber-iOS/Uber-iOS/Presentation/ViewController/HomeViewController.swift
Labels: 🍏영주🍏, feat

#33 [Hotfix] ㅅi크..한 🅢🅔🅒🅡🅔🅣 파일 삭제
  Uber-iOS/Secrets.xcconfig
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
Labels: 🍎휘원🍎, hotfix

#30 [Feat] Network Base 세팅
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
  Uber-iOS/Uber-iOS/Network/Base/BaseResponse.swift
  Uber-iOS/Uber-iOS/Network/Base/BaseService.swift
  Uber-iOS/Uber-iOS/Network/Base/EndPoint.swift
  Uber-iOS/Uber-iOS/Network/Base/HTTPMethodType.swift
  Uber-iOS/Uber-iOS/Network/Base/NetworkError.swift
  Uber-iOS/Uber-iOS/Network/Base/NetworkLogger.swift
  Uber-iOS/Uber-iOS/Network/Model/SearchResponse.swift
  Uber-iOS/Uber-iOS/Network/Service/SearchService.swift
  Uber-iOS/Uber-iOS/Presentation/RecentSearchView/SearchKeywordEntity.swift
Labels: 🍎휘원🍎, feat

#28 [Feat] 출발지, 도착지 텍스트 필드 UI
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/TextField/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/TextField/departure.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/TextField/departure.imageset/departure.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/TextField/place.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/TextField/place.imageset/place.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/account.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/account.imageset/account.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/activity.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/activity.imageset/activity.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/banner.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/banner.imageset/banner.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/calendar.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/calendar.imageset/calendar.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/car.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/car.imageset/car.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/home.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/home.imageset/home.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/next.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/next.imageset/next.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/service.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/service.imageset/service.png
  Uber-iOS/Uber-iOS/Presentation/View/SearchLocationTextField.swift
  Uber-iOS/Uber-iOS/Presentation/ViewController/HomeViewController.swift
  Uber-iOS/Uber-iOS/Presentation/ViewController/ViewController.swift
Labels: 🍏영주🍏, feat

#31 [Feat] 시간 선택 뷰 구현
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
  Uber-iOS/Uber-iOS/Presentation/CommonView/TextField/SearchLocationTextField.swift
  Uber-iOS/Uber-iOS/Presentation/Home/DiscountBannerView.swift
  Uber-iOS/Uber-iOS/Presentation/Home/HomeHeaderView .swift
  Uber-iOS/Uber-iOS/Presentation/Home/HomeViewController.swift
  Uber-iOS/Uber-iOS/Presentation/Home/ReserveBannerView.swift
  Uber-iOS/Uber-iOS/Presentation/Home/ServiceButtonView.swift
  Uber-iOS/Uber-iOS/Presentation/Home/TabBar.swift
  Uber-iOS/Uber-iOS/Presentation/PickupTime/PickupTimeViewController.swift
  Uber-iOS/Uber-iOS/Presentation/ViewController/ViewController.swift
Labels: 🍏영주🍏, feat

#24 [Feat] 차량 선택 화면 UI구현
  Uber-iOS/Uber-iOS/Presentation/VehicleSelection/VehicleSelectionButton.swift
  Uber-iOS/Uber-iOS/Presentation/VehicleSelection/VehicleSelectionViewController.swift
Labels: 🧃석기🧃, feat

#36 [Feat] CustonNavigationBar 추가
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
  Uber-iOS/Uber-iOS/Application/AppDelegate.swift
  Uber-iOS/Uber-iOS/Application/SceneDelegate.swift
  Uber-iOS/Uber-iOS/Global/Base/BaseViewController.swift
  Uber-iOS/Uber-iOS/Global/Extension/UINavigationController+.swift
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/backButton.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/backButton.imageset/backButton.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/backButton.imageset/icon_36px@2x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/backButton.imageset/icon_36px@3x.png
  Uber-iOS/Uber-iOS/Presentation/CommonView/Navigation/UberNavigationBar.swift
  Uber-iOS/Uber-iOS/Presentation/Reservation/ReservationInfoViewController.swift
Labels: 🧃석기🧃, feat

#40 [Feat] 택시 종류 API 연동
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
  Uber-iOS/Uber-iOS/Global/Extension/UIImageView+.swift
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/home/banner.imageset/banner.png
  Uber-iOS/Uber-iOS/Global/Setting/Info.plist
  Uber-iOS/Uber-iOS/Network/Model/TaxiResponse.swift
  Uber-iOS/Uber-iOS/Network/Service/VehicleService.swift
  Uber-iOS/Uber-iOS/Presentation/CommonView/Reserve/ReserveInfoView.swift
  Uber-iOS/Uber-iOS/Presentation/Reservation/ReservationInfoViewController.swift
  Uber-iOS/Uber-iOS/Presentation/VehicleSelection/TaxiInfoEntity.swift
  Uber-iOS/Uber-iOS/Presentation/VehicleSelection/VehicleSelectionButton.swift
  Uber-iOS/Uber-iOS/Presentation/VehicleSelection/VehicleSelectionViewController.swift
Labels: 🧃석기🧃, feat

#43 [Feat] 예약 정보 화면 UI 수정
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/deleteBlack.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/deleteBlack.imageset/deleteButton.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/deleteBlack.imageset/icon_36px@2x.png
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/deleteBlack.imageset/icon_36px@3x.png
  Uber-iOS/Uber-iOS/Presentation/CommonView/TextField/SearchLocationTextField.swift
  Uber-iOS/Uber-iOS/Presentation/Reservation/DiscountCard.swift
  Uber-iOS/Uber-iOS/Presentation/Reservation/ReservationInfoViewController.swift
  Uber-iOS/Uber-iOS/Presentation/Reservation/VehicleInfoButton.swift
Labels: 🧃석기🧃, feat

#42 [Feat] ReserveNotice 뷰 UI
  Uber-iOS/Uber-iOS/Presentation/ReserveNotice/ReserveNoticeType.swift
  Uber-iOS/Uber-iOS/Presentation/ReserveNotice/ReserveNoticeView.swift
  Uber-iOS/Uber-iOS/Presentation/ReserveNotice/ReserveNoticeViewController.swift
Labels: 🍎휘원🍎, feat

#44 [Feat] 출발지, 도착지 텍스트필드 api 연결
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/xmark.imageset/Contents.json
  Uber-iOS/Uber-iOS/Global/Resources/Resources/Assets.xcassets/xmark.imageset/xmark.png
  Uber-iOS/Uber-iOS/Global/Setting/Info.plist
  Uber-iOS/Uber-iOS/Network/Model/LocationRequest.swift
  Uber-iOS/Uber-iOS/Network/Service/LocationService.swift
  Uber-iOS/Uber-iOS/Presentation/CommonView/TextField/SearchLocationTextField.swift
  Uber-iOS/Uber-iOS/Presentation/ViewController/ViewController.swift
Labels: 🍏영주🍏, feat

#47 [Feat] 예약 검색 뷰 UI + 개별 삭제 / 전체 삭제 API
  Uber-iOS/Uber-iOS.xcodeproj/project.pbxproj
  Uber-iOS/Uber-iOS/Global/Setting/Info.plist
  Uber-iOS/Uber-iOS/Network/Base/BaseService.swift
  Uber-iOS/Uber-iOS/Network/Base/EndPoint.swift
  Uber-iOS/Uber-iOS/Network/Model/SearchResponse.swift
  Uber-iOS/Uber-iOS/Network/Service/SearchService.swift
  Uber-iOS/Uber-iOS/Presentation/RecentSearchView/RecentSearchCell.swift
  Uber-iOS/Uber-iOS/Presentation/RecentSearchView/RecentSearchViewController.swift
  Uber-iOS/Uber-iOS/Presentation/Reservation/ReservationInfoViewController.swift
Labels: 🍎휘원🍎, feat
